# SPDX-License-Identifier: GPL-2.0
dtb-$(CONFIG_ARCH_MA35D1)    += myb-lma35dx-base.dtb \
				myb-lma35dx-qspi.dtb \
				myb-lma35dx-emmc.dtb \
				myt-lma35dx-base.dtb \
				myt-lma35dx-qspi.dtb \
				myt-lma35dx-emmc.dtb

always          := $(dtb-y)
clean-files     := *.dtb

